# Generated by Django 5.1 on 2025-03-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('occupation', models.CharField(max_length=255)),
                ('activity_level', models.CharField(max_length=50)),
                ('work_schedule', models.CharField(max_length=50)),
                ('travel_frequency', models.CharField(max_length=50)),
                ('physical_activities', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('therapies', models.TextField(blank=True, null=True)),
                ('injuries', models.TextField(blank=True, null=True)),
                ('family_diseases', models.BooleanField()),
                ('smoking_status', models.BooleanField()),
                ('diet_type', models.CharField(max_length=50)),
                ('fitness_goals', models.TextField()),
                ('training_frequency', models.IntegerField()),
                ('preferred_training_time', models.CharField(max_length=50)),
                ('expectations', models.TextField()),
                ('agreed_terms', models.BooleanField()),
                ('phone_number', models.CharField(max_length=15)),
                ('health_reports', models.FileField(blank=True, null=True, upload_to='health_reports/')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='attached_files/')),
            ],
        ),
    ]
